source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RXPiOS_Example' do
  platform :ios, '9.0'

  pod "RXPiOS", :path => "../"
end

target 'RXPiOS_Tests' do
  platform :ios, '9.0'

  pod "RXPiOS", :path => "../"
end
